name: Analyze Repository Languages with Linguist

on:
  workflow_call:
    inputs:
      workdir:
        description: "The path to the working directory"
        required: false
        type: string
        default: "."

jobs:
  linguist-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install Linguist gem
        run: gem install github-linguist

      - name: Run Linguist analysis
        run: |
          echo "Linguist analysis result:"
          linguist ${{ inputs.workdir }}