name: Build Docker Image

on:
  workflow_call:
    inputs:
      workdir:
        description: "The path to the Dockerfile"
        required: true
        type: string
      dockerfile:
        description: "The path to the Dockerfile"
        required: true
        type: string
      image_name:
        description: "The name of the Docker image"
        required: true
        type: string
      version:
        description: "The version tag for the Docker image"
        required: true
        type: string
      language:
        description: "Programming language (go, python, node)"
        required: true
        type: string
      language_version:
        description: "Version of the programming language"
        required: true
        type: string
      submodule_path:
        description: "Path to the Git submodule (for Go projects)"
        required: false
        type: string
      submodule_version:
        description: "Version/tag of the submodule to checkout"
        required: false
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up Go
        if: ${{ inputs.language == 'go' }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ inputs.language_version }}

      - name: download submodule
        if: ${{ inputs.language == 'go' && inputs.submodule_path }}
        run: git submodule update --init --recursive ${{ inputs.submodule_path }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build Docker image
        run: docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -f ${{ inputs.dockerfile }} ${{ inputs.workdir }}
      
      - name: tag Docker image latest
        run: docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
      
      - name: Push Docker image
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        