name: Build Docker Image and Create Release

on:
  workflow_call:
    inputs:
      workdir:
        description: "The path to the working directory"
        required: true
        type: string
      dockerfile:
        description: "The path to the Dockerfile"
        required: true
        type: string
      image_name:
        description: "The name of the Docker image"
        required: true
        type: string
      version:
        description: "The version tag for the Docker image"
        required: true
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_VERSION: ${{ inputs.version }}

jobs:
  linguist-analysis:
    uses: slice-soft/ss-pipeline/.github/workflows/analyze-code.yml@v0
    with:
      workdir: .
    secrets: inherit
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Enable Docker BuildKit
        run: echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV

      - name: Set up SSH key for Docker secret
        id: setup_ssh
        run: |
          # Crear archivo temporal con la clave privada
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa
          chmod 600 id_rsa
        shell: bash

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build Docker image
        run: |
          docker build --no-cache \
            --secret id=ssh_private_key,src=id_rsa \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }} \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
            -f ${{ inputs.dockerfile }} \
            ${{ inputs.workdir }}
        env:
          DOCKER_BUILDKIT: 1

      - name: Push Docker image with version tag
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
        
      - name: Push Docker image with latest tag
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Clean up SSH key
        if: always()
        run: rm -f id_rsa

  create-release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.IMAGE_VERSION }}
          release_name: v${{ env.IMAGE_VERSION }}
          draft: false
          prerelease: false
