name: Release

on:
  workflow_call:
    outputs:
      release_created:
        value: ${{ jobs.release-please.outputs.release_created }}
      tag_name:
        value: ${{ jobs.release-please.outputs.tag_name }}

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}

    steps:
      - name: Run release-please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - name: Checkout repository
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v6

      - name: Update Major Tag
        if: ${{ steps.release.outputs.release_created }}
        run: |
          major_tag=$(echo "${{ steps.release.outputs.tag_name }}" | cut -d. -f1)
          git tag -f $major_tag
          git push origin $major_tag --force
