name: Release Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release-pipeline:
    uses: slice-soft/ss-pipeline/.github/workflows/create-release.yml
    secrets: inherit