name: Release Pipeline

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Tag
        id: tag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: main
          release_strategy: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        uses: ./.github/workflows/reusable-workflow.yml
        with:
          tag: ${{ steps.tag.outputs.tag }}
        secrets: inherit
        permissions:
          contents: read
          packages: write
          attestations: write
          id-token: write
