name: "Node Requirements Pipeline"
on:
  workflow_call:
    inputs:
      node-version:
        description: "Node.js version to use"
        required: true
        default: "22"
        type: string
      project-type:
        description: "Type of Node.js project (e.g., library, application)"
        required: true
        default: "library"
        type: string
      package-file:
        description: "Path to the package file (e.g., package.json)"
        required: true
        default: "./package.json"
        type: string

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '${{ inputs.node-version }}'
      - name: Restore Cache
        uses: actions/cache@v3
        id: restore-cache
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: npm-${{ env.cache-name}}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-${{ env.cache-name }}
      - name: Install dependencies
        if: steps.restore-cache.outputs.cache-hit != 'true'
        run: npm ci

  tests:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '${{ inputs.node-version }}'
      - name: Restore Cache
        uses: actions/cache@v3
        id: restore-cache
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: npm-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-${{ env.cache-name }}
      - name: Run tests
        run: npm test

  validate-package-version:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '${{ inputs.node-version }}'
      - name: Validate package version
        run: |
          current_version=$(jq -r '.version' '${{ inputs.package-file }}')
          echo "Current version: $current_version"
          latest_release=$(npm view $(jq -r '.name' '${{ inputs.package-file }}') version)
          echo "Latest release version: $latest_release"
      
  code-analysis:
    needs: [validate-package-version]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '${{ inputs.node-version }}'
      - name: Restore Cache
        uses: actions/cache@v3
        id: restore-cache
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: npm-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-${{ env.cache-name }}
      - name: Run Code Analysis
        run: npm run lint