name: "Node Requirements Pipeline"
on:
  workflow_call:
    inputs:
      node-version:
        description: "Node.js version to use"
        required: true
        default: "22"
        type: string

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '${{ inputs.node-version }}'
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ inputs.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ inputs.node-version }}-
      - name: Install dependencies
        run: npm install
      - name: Upload dependencies
        uses: actions/upload-artifact@v3
        with:
          name: deps
          path: node_modules

  build:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '${{ inputs.node-version }}'
      - name: Download dependencies
        uses: actions/download-artifact@v3
        with:
          name: deps
          path: node_modules
      - name: Build project
        run: npm run build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '${{ inputs.node-version }}'
      - name: Download dependencies
        uses: actions/download-artifact@v3
        with:
          name: deps
          path: node_modules
      - name: Run tests with coverage
        run: npm run test

  code-analysis:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '${{ inputs.node-version }}'
      - name: Download dependencies
        uses: actions/download-artifact@v3
        with:
          name: deps
          path: node_modules
      - name: Run lint
        run: npm run lint