name: Validate PR
on:
  workflow_call:
jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check semver label
        run: |
          labels='${{ toJson(github.event.pull_request.labels.*.name) }}'
          if echo "$labels" | grep -qE '"patch"|"minor"|"major"'; then
            echo "✅ Semver label found"
          else
            echo "❌ Add a label: patch, minor or major"
            exit 1
          fi