name: Validate PR
on:
  workflow_call:
jobs:
  validate-title:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title (conventional commits)
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}